Output kubectl_crdlist.gif

Require echo

Set Shell "bash"
Set FontSize 32
Set Width 2500
Set Height 1200

Type "./dist/kubectl-crdlist" Sleep 500ms  Enter
Type "/" Sleep 500ms
Type "monitoring" Sleep 500ms  Enter
Type "g" Sleep 2500ms
Enter
Sleep 2500ms
Escape Sleep 500ms
Escape Sleep 500ms
Type "/" Sleep 500ms
Type "virtualservice" Sleep 500ms  
Enter Sleep 500ms 
Enter Sleep 500ms 
Enter Sleep 2500ms 
Type "q" Sleep 500ms

Sleep 3s
